### ISSUE TITLE
[ISSUE] Scaffold check issue

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [PhoenixDiscord/MatrixConfig#2]
**Describe the issue**
The config gets suspicious of scaffold if people bridge quickly (such as ninja bridging like shifting and unshifting while bridging to bridge quicker.

**To Reproduce**
1. Try to bridge quickly such as ninja bridging or something.
2. The config picks you up for placing blocks too quickly

**Expected behavior**
The config should be a bit more conservative with this check to ensure it's not false kicking someone for using strategies to bridge quicker.

**Screenshots**
![Blocks](https://i.imgur.com/kUTF2z8.png)
![Blocks2](https://i.imgur.com/sKIUxEB.png)

**Server Info**
- Paper version 1.15.2
- 1.8 pvp

**Additional context**
I'm using your default config, not the skywars one. Matrix logs:
```
(20:13:59) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:3 ping:48 tps:20.0 component: sfd.simple
(20:14:00) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:6 ping:48 tps:20.0 component: sfd.simple
(20:14:00) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:9 ping:48 tps:20.0 component: sfd.simple
(20:14:00) Execute command: matrix notify BennyDoesStuff tried to bridge blocks quickly (Scaffold)
(20:22:36) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:3 ping:41 tps:20.0 component: sfd.simple
(20:22:38) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:6 ping:41 tps:20.0 component: sfd.simple
(20:22:38) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:9 ping:41 tps:20.0 component: sfd.simple
(20:22:38) Execute command: matrix notify BennyDoesStuff tried to bridge blocks quickly (Scaffold)
(20:22:39) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:12 ping:41 tps:20.0 component: sfd.simple
(20:22:43) BennyDoesStuff failed Scaffold check | scaffold | type: simple (+3) | vl:15 ping:41 tps:20.0 component: sfd.simple
(20:22:43) Execute command: matrix notify BennyDoesStuff tried to bridge blocks quickly (Scaffold) #2
```

**Comment by gogorz** [comment]
I will verify if this happens in a couple of hours; I'm busy right now.

**Comment by gogorz** [comment]
I made the simple check's vl smaller which should decrease false positives at the cost of the detection speed. I recommend you to try the updated config (in the repo) on a test server to verify if the false positives are still there.

**Comment by gogorz** [comment]
After setting the VL of the simple module to 1 the scaffold check still seems to be detected, but this causes Tower (LiquidBounce/Jump type) to get detected after a very slow amount of time. I'd recommend reporting the false positives to the developer of Matrix as this can't be fixed without allowing for bypasses and slow detection.

**Comment by gogorz** [comment]
The simple module has been removed in Matrix 4.7.10, which means the false positives are gone.
